### ISSUE TITLE
Hard-code gamma-0 radiometry in area map xml (if appropriate)

### ISSUE THREAD

**Issue by hjkristenson** [ASFHyP3/hyp3-metadata-templates#65]
Current xml populates radiometry in area map xml dynamically based on requested radiometry for the RTC product, but it may be the case that the area map is *always* in gamma-0. Check with @talogan to verify, and change if appropriate.

**Comment by talogan** [comment]
Currently, the scattering area file that we create is in gamma-0 projection
whether the output is in sigma-0 or gamma-0.

We could get  a sigma-0 scattering area image if we want to
modify mk_geo_radcal2 - it currently does not exercise the sigma-0
scattering area image option of pixel_area as it is not needed by
the program.  Instead the program uses the sigma0_ratio and the
sig2gam_ratio instead.


*pixel_area <MLI_par> <DEM_par> <DEM> <lookup_table> <ls_map> <inc_map>
<pix_sigma0> [pix_gamma0] [nstep] [area_fact] [sigma0_ratio] [gamma0_ratio]
[sig2gam_ratio]*

pix_sigma0 is the sigma-0 scattering area

pix_gamm0 is the gamma-0 scattering area

As you can see below, the pix_sigma0 image is not created by either of the
calls to pixel_area (- means ignore the parameter).

Mode 0 - Create the simulated SAR image, which is the same as pix_gamma0

*  execute("pixel_area $mli_par $dem_seg_par $dem_seg $gc0 $ls_map $inc_map
- $pix_gamma0 20 0.2", $log);*


Mode 3 - Create final ratio_images to be used for RTC

*execute("pixel_area $mli_par $dem_seg_par $dem_seg $gc1 $ls_map $inc_map -
$pix_gamma0 20 1.0 $sigma0_ratio - $sig2gam_ratio")*
